$MODEL GagarinSat_v0
# 
# template file: Template.tpl
# ESATAN-TMS 2020, run date 3:34 Sat 8 May 2021
# Model name: GagarinSat_v0        Analysis case: Case_00
  $MODEL INS_PLD2
#
    $LOCALS
    # GENCODE LOCALS - DO NOT REMOVE 
#
    $NODES
    # GENCODE NODES - DO NOT REMOVE 
#
    $CONDUCTORS
    # GENCODE CONDUCTORS - DO NOT REMOVE 
#
    $CONSTANTS
    # GENCODE CONSTANTS - DO NOT REMOVE 
#
    $ARRAYS
    # GENCODE ARRAYS - DO NOT REMOVE 
#
    $EVENTS
    # GENCODE EVENTS - DO NOT REMOVE 
#
    $SUBROUTINES
    # GENCODE SUBROUTINES - DO NOT REMOVE 
C
    $INITIAL
      GENMOR
    # GENCODE BOUNDARY_CONDS - DO NOT REMOVE 
    # GENCODE INITIAL - DO NOT REMOVE 
C
    $VARIABLES1
    # GENCODE VARIABLES1 - DO NOT REMOVE 
C
    $VARIABLES2
    # GENCODE VARIABLES2 - DO NOT REMOVE 
C
  $ENDMODEL INS_PLD2
  $MODEL INS_PLD1
#
    $LOCALS
    # GENCODE LOCALS - DO NOT REMOVE 
#
    $NODES
    # GENCODE NODES - DO NOT REMOVE 
#
    $CONDUCTORS
    # GENCODE CONDUCTORS - DO NOT REMOVE 
#
    $CONSTANTS
    # GENCODE CONSTANTS - DO NOT REMOVE 
#
    $ARRAYS
    # GENCODE ARRAYS - DO NOT REMOVE 
#
    $EVENTS
    # GENCODE EVENTS - DO NOT REMOVE 
#
    $SUBROUTINES
    # GENCODE SUBROUTINES - DO NOT REMOVE 
C
    $INITIAL
      GENMOR
    # GENCODE BOUNDARY_CONDS - DO NOT REMOVE 
    # GENCODE INITIAL - DO NOT REMOVE 
C
    $VARIABLES1
    # GENCODE VARIABLES1 - DO NOT REMOVE 
C
    $VARIABLES2
    # GENCODE VARIABLES2 - DO NOT REMOVE 
C
  $ENDMODEL INS_PLD1
#
  $LOCALS
  # GENCODE LOCALS - DO NOT REMOVE 
#
  $NODES
  # GENCODE NODES - DO NOT REMOVE 
#
  $CONDUCTORS
  # GENCODE CONDUCTORS - DO NOT REMOVE 
#
  $CONSTANTS
  # GENCODE CONSTANTS - DO NOT REMOVE 
#
  $ARRAYS
  # GENCODE ARRAYS - DO NOT REMOVE 
#
  $EVENTS
  # GENCODE EVENTS - DO NOT REMOVE 
#
  $SUBROUTINES
  # GENCODE SUBROUTINES - DO NOT REMOVE 
C
  $INITIAL
      GENMOR
  # GENCODE BOUNDARY_CONDS - DO NOT REMOVE 
  # GENCODE INITIAL - DO NOT REMOVE 
C
  $EXECUTION

C
      TIMEND=6059.2857
      OUTINT=605.92857
      NLOOP=100
      RELXCA=0.01
      DTIMEI=1.0
      CALL SOLCYC('SLCRNC',0.1D0,0.05D0,6059.2857D0,100,' ','NONE')
C
      CALL SLCRNC
C
  $VARIABLES1
  # GENCODE VARIABLES1 - DO NOT REMOVE 
C
  $VARIABLES2
  # GENCODE VARIABLES2 - DO NOT REMOVE 
C
  $OUTPUTS
      CALL PRNDTB(' ', 'L, T, QS, QE, QA, QI, C', CURRENT)
C
      CALL DMPTMD(' ', 'NODES, CONDUCTORS, CONSTANTS', CURRENT, ' ')

  # GENCODE OUTPUTS - DO NOT REMOVE 
C
$ENDMODEL GagarinSat_v0
